feat: add junit report

diff --git a/.github/workflows/go_app_push_main.yml b/.github/workflows/go_app_push_main.yml
--- a/.github/workflows/go_app_push_main.yml
+++ b/.github/workflows/go_app_push_main.yml
@@ -50,10 +50,21 @@ jobs:
       - name: go vet
         run: find . -name vendor -prune -o -name go.mod -print | xargs -n1 dirname
           | xargs -n1 -I{} bash -c "pushd {}; go vet ./..."
+      # Install go-junit-report to format test results.
+      - name: Install go-junit-report
+        run: go install github.com/jstemmer/go-junit-report@latest
       # Run unit test for evet Go module.
       - name: go test
         run: find . -name vendor -prune -o -name go.mod -print | xargs -n1 dirname
           | xargs -n1 -I{} bash -c "pushd {}; go test -coverprofile=coverage.txt --race -v ./..."
+          | go-junit-report -set-exit-code > junit_report.xml || true
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Test Report   # Name of the check run which will be created
+          path: junit_report.xml   # Path to test results
+          reporter: java-junit        # Format of test results
       - name: Upload test coverage results to Codecov
         uses: codecov/codecov-action@v4
         with:
